Admin/__init__.py
from flask import Blueprint

admin = Blueprint('Admin',__name__,static_url_path="/static", static_folder="static", template_folder="templates")

from . import views

Admin/views.py
from werkzeug.security import generate_password_hash,check_password_hash
from flask import render_template,request,redirect,session,url_for
from settings import Students,Admins,db
from .verify import tokenCheck
from Admin import admin
import os


if "SECRET_TOKEN" in os.environ:
    SECRET_TOKEN = os.environ['SECRET_TOKEN']
else:
    SECRET_TOKEN = 'this-is-secret'

@admin.route('/thank-you')
def thankyou():
    if "secret_token" in session:
        session.pop("secret_token", None)
        return render_template('thankyou.html')
    return render_template('thankyou.html')


@admin.route('/add-secret', methods=['GET','POST'])
def secret():
    session.pop("secret_token", None)
    if request.method == "POST":
        secret_token = request.form['secret_token']
        if tokenCheck(secret_token):
            if secret_token == SECRET_TOKEN:
                session["secret_token"] = secret_token
                return redirect(url_for('Admin.register'))
            else:
                return '<h1> Sorry, We can not proceed your request  :( </h1>'
        else:
            return redirect('/admin')
    return render_template('secret.html')


@admin.route('/registration/fg38h43ibcf33owlqpw92gwqe', methods=['GET','POST'])
def register():
    if "secret_token" in session:
        if request.method == "POST":
            adminusername = request.form['adminusername']
            adminemail = request.form['adminemail']
            adminpassword = request.form['adminpassword']
            hash_password = generate_password_hash(adminpassword)
            chk_point = Admins.query.filter_by(adminEmail=adminemail).first()
            if chk_point is None:
                forSubbmit = Admins(adminUser=adminusername,adminEmail=adminemail,adminPassword=hash_password)
                db.session.add(forSubbmit)
                db.session.commit()
                return redirect(url_for('Admin.thankyou'))
            else:
                return '<h1> Sorry ! This User is already exist. Please Use a different Email id :( </h1>'
        return render_template('admin_register.html')
    session.pop("secret_token", None)
    return redirect(url_for('Admin.admin_login'))
    

@admin.route('/login', methods=['GET','POST'])
def admin_login():
    if request.method == "POST":
        useremail = request.form['userEmail']
        password = request.form['password']
        found_user = Admins.query.filter_by(adminEmail=useremail).first_or_404(description='Wrong Input ! Please Enter correct Information')
        cond = check_password_hash(found_user.adminPassword,password)
        if cond:
            session["user"] = useremail
            session["password"] = password
            return redirect(url_for('Admin.dashboard', usr=found_user.adminUser))
        else:
            return redirect(url_for('Admin.admin_login'))
    elif "user" in session:
        found_user = Admins.query.filter_by(adminEmail=session["user"]).first_or_404(description='Wrong Input ! Please Enter correct Information')
        return redirect(url_for('Admin.dashboard', usr=found_user.adminUser))
    return render_template('admin_login.html')


@admin.route('/dashboard/<usr>')
def dashboard(usr):
    if "user" in session:
        complains = Students.query.order_by(Students.date).all()
        complains.reverse()
        return render_template('dashboard.html', user_display=usr, total_compNo=len(complains), all_complains=complains)
    else:
        return redirect(url_for('Admin.admin_login'))


@admin.route('/update/<id>')
def update(id):
    if ("user" in session):
        updt = Students.query.get(id)
        updt.isViewed = 'True'
        db.session.commit()
        found_user = Admins.query.filter_by(adminEmail=session["user"]).first_or_404()
        return redirect(url_for('Admin.dashboard', usr=found_user.adminUser))
    else:
        return redirect('/admin')


@admin.route('/delete/<id>')
def delete(id):
    if "user" in session:
        dlt = Students.query.get(id)
        db.session.delete(dlt)
        db.session.commit()
        found_user = Admins.query.filter_by(adminEmail=session["user"]).first_or_404()
        return redirect(url_for('Admin.dashboard', usr=found_user.adminUser))
    else:
        return redirect('/admin')


@admin.route('/logout')
def logout():
    if "user" in session:
        session.pop("user", None)
        session.pop("password", None)
        return redirect(url_for('Admin.admin_login'))
    return render_template('admin_login.html')
    

Admin/templates/admin_login.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>Admin | Login</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <meta name="msapplication-config" content="/docs/4.4/assets/img/favicons/browserconfig.xml">
    <meta name="theme-color" content="#563d7c">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{{ url_for('Admin.static', filename='style.css') }}" rel="stylesheet">
  </head>
  <body class="text-center">
    <form class="form-signin" action="{{url_for('Admin.admin_login')}}" method="POST">
  <h1 class="h3 mb-3 font-weight-normal">Please Login</h1>
  <label for="userEmail" class="sr-only">Email address</label>
  <input type="email" id="userEmail" name="userEmail" class="form-control" placeholder="Email address" required autofocus><br>
  <label for="password" class="sr-only">Password</label>
  <input type="password" id="password" name="password" class="form-control" placeholder="Password" required>
  <div class="checkbox mb-3">
    <label>
      <input type="checkbox" value="remember-me"> Remember me
    </label>
  </div>
  <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
  <p class="mt-5 mb-3 text-muted">&copy; 2020-2022</p>
</form>
</body>
</html>

Admin/templates/admin_register.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>Admin | Registration</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <meta name="msapplication-config" content="/docs/4.4/assets/img/favicons/browserconfig.xml">
    <meta name="theme-color" content="#563d7c">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{{ url_for('Admin.static', filename='style.css') }}" rel="stylesheet">
  </head>
  <body class="text-center">
    <form class="form-signin" action="{{url_for('Admin.register')}}" method="POST">
  <h1 class="h3 mb-3 font-weight-normal">New Registration</h1>
  <label for="adminusername" class="sr-only">Enter Name</label>
  <input type="text" id="adminusername" name="adminusername" class="form-control" placeholder="Name" required autofocus><br>
  <label for="adminemail" class="sr-only">Email address</label>
  <input type="email" id="adminemail" name="adminemail" class="form-control" placeholder="Email address" required autofocus><br>
  <label for="adminpassword" class="sr-only">Password</label>
  <input type="password" id="adminpassword" name="adminpassword" class="form-control" placeholder="Password" required>
  <div class="checkbox mb-3">
    <label>
      <input type="checkbox" value="remember-me"> Remember me
    </label>
  </div>
  <button class="btn btn-lg btn-primary btn-block" type="submit">Register</button>
  <p class="mt-5 mb-3 text-muted">&copy; 2020-2022</p>
</form>
</body>
</html>

Admin/templates/dashboard.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Dashboard Page</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-md sticky-top navbar-light bg-default">
        <a class="navbar-brand" href="#">
          <h2 style="font-family: fantasy;">Complain's Dashboard</h2>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
          aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active nav-link btn-lg p-2 my-2 mx-5">
              <b>Hi, {{user_display}}</b>
            </li>
            <li class="nav-item">
              <a href="{{url_for('Admin.logout')}}" class="nav-link btn btn-danger btn-lg p-2 m-2" style="border-radius: 30px;"><b style="color: white;">Log Out</b></a>
            </li>

          </ul>
        </div>
      </nav>


    <div class="table-responsive m-auto" style="width: 92%;">
      <h5><code> Total number of Active Complain is :  </code>{{total_compNo}}</h5>
        <table class="table table-bordered text-center mx-auto">
            <thead class="thead bg-primary text-light">
              <tr>
                <th scope="col">Date</th>
                <th scope="col">Status Code</th>
                <th scope="col">Student Name</th>
                <th scope="col">Mail id</th>
                <th scope="col">Roll No.</th>
                <th scope="col">Department</th>
                <th scope="col">Semester</th>
                <th scope="col">Year of Study</th>
                <th scope="col">Against To</th>
                <th scope="col">Viewed</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody class="text-center">

            <!-- Start of jinja block -->
            {% if (total_compNo != 0) %}
              {% for complain in all_complains %}
              <tr>
                <th scope="row">{{complain.date}}</th>
                <td>{{complain.code}}</td>
                <td>{{complain.fullName}}</td>
                <td>{{complain.email}}</td>
                <td>{{complain.roll}}</td>
                <td>{{complain.department}}</td>
                <td>{{complain.semester}}</td>
                <td>{{complain.year}}</td>
                <td>{{complain.addressTo}}</td>
                <td>
                  {% if complain.isViewed == 'True' %}
                  &#9989;
                  {% endif %}
                </td>
                <td>
                  <a href="#" class="btn btn-success mx-1 m-1" style="border-radius: 20px;" data-toggle="modal" data-target="#viewDetails{{complain.id}}"><b>View It</b></a>
                  <a href="{{url_for('Admin.update',id=complain.id)}}" class="btn btn-warning mx-1 m-1" style="border-radius: 20px;">Mark As Viewed</a>
                  <a href="{{url_for('Admin.delete',id=complain.id)}}" class="btn btn-dark mx-1 m-1" style="border-radius: 20px;" onclick="return confirm('Are you sure you want to delete this item?');">Delete</a>
                </td>
              </tr>
              <!-- Modal -->
              <div class="modal fade bd-example-modal-lg" id="viewDetails{{complain.id}}" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                <div class="modal-dialog modal-lg" role="document">
                  <div class="modal-content full_modal-content">
                    <div class="modal-header">
                      <p class="modal-title">Ref. Id/Status Code : <b>{{complain.code}}</b></p>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-header">
                      <h3 class="modal-title" id="staticBackdropLabel"><b style="color: blue;"><u>Title :</u></b> {{complain.title}}</h3>
                    </div>
                    <div class="modal-body">
                      <!-- add safe filter -->
                      {{complain.body|safe}}
                    </div>
                    <div class="modal-footer">                     
                      <button type="button" class="btn btn-primary btn-lg" data-dismiss="modal">Close</button>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
            {% endif%}
     <!-- End of jinja block -->


            </tbody>
          </table>

          {% if (total_compNo == 0) %}
          <div class="text-center">
            <h3 class="text-success"> Good job ! </h3>
            <img src="../static/emoji.jpg" alt="emoji"/>
            <h5 class="text-success"> You have no more complain to solve. </h5>
          </div>
          {% endif %}

    </div>

      
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script> 
    
  </body>
</html>

Admin/templates/secret.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Secret Token</title>
</head>
<body>
    <br><br><br><br>
    <div class="container mt-5">
        <form action="#" method="POST">
            <div class="form-group" style="width: auto;" >
              <label for="secret_token" class="sr-only">Password</label>
              <input type="password" class="form-control" name="secret_token" id="secret_token" placeholder="SECRET TOKEN">
            </div><br>
            <button type="submit" class="btn btn-primary">Confirm identity</button>
          </form>

    </div>
    
</body>
</html>

Admin/templates/thankyou.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Thank You</title>
  </head>
  <body>
    <div class="container text-center mt-5">
        <h1 style="color: red;"> Thank You ! </h1>
        <h3 style="color: green;"><i> You have done successfully. </i></h3>
        <div class="spinner-grow text-info" style="width: 36rem; height: 36rem;" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
  </body>
</html>